<!DOCTYPE html>  
<html>  
<head>
    <title>Two Friends and the Bear</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="ShortStoriesStyle.css">
	<style>
		body {
			margin: 100px;
		}
	</style>
</head>
<body style="background-color:#FFFFE0">
    <h2>Two Friends and the Bear</h2>
    <center><img src = "TwoFriendsAndTheBear.jpg">
    <p>
        Once there were two friends who were crossing the jungle. After some time they saw a bear coming towards them.<br>
		Then, one of the friends quickly climbed the nearby tree and the other one did not know how to climb the tree.<br> 
		So he lays down on the ground holding his breath. The bear reaches near him and sniffs him in the ear.<br>
		After some time bear left the place, thinking the man is dead. Now the other friend climbs down and asked his<br> 
		friend, what did bear said to him in his ear? He replied,” to be safe from the fake friends.”<br>
    </p>
</body>
</html>
