<!DOCTYPE html>  
<html>  
<head>
	<title>The Cows and the Tiger</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="ShortStoriesStyle.css">
	<style>
		body {
			margin: 100px;
		}
	</style>
</head>
<body style="background-color:#FFFFE0">
    <h2>The Cows and the Tiger</h2>
    <center><img src = "TheCowsAndTheTiger.jpg">
    <p>
        Four cows lived in a forest near a meadow. They were good friends and did everything together.<br>
		They grazed together and stayed together, because of which no tigers or lions were able to kill them for food.<br>
		But one day, the friends fought and each cow went to graze in a different direction. A tiger and a lion saw this<br> 
		and decided that it was the perfect opportunity to kill the cows. They hid in the bushes and surprised the cows<br> 
		and killed them all, one by one.<br>
    </p>
</body>
</html>
