<!DOCTYPE html>  
<html>  
<head>
	<title>The Crow and the Peacock</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="ShortStoriesStyle.css">
	<style>
		body {
			margin: 100px;
		}
	</style>
</head>
<body style="background-color:#FFFFE0">
    <h2>The Crow and the Peacock</h2>
    <center><img src = "TheCrowAndThePeacock.jpg">
    <p>
        Once there was a crow who wishes to be colorful and beautiful like other birds.<br> 
		He then went to the parrot and shared his thoughts. But parrot said peacock is<br>  
		most beautiful bird so talk to him. Then the crow went to the peacock and told him<br>  
		about his looks. Then the peacock replied,” You are the luckiest bird that has been<br>  
		never caged in life and we because of our beauty stay caged, and you are always free.”<br> 
		After listening to this, crow realized his mistake and thanked God for making him<br>  
		like this and he flew away happily.<br>  
    </p>
</body>
</html>
