<!DOCTYPE html>  
<html>  
<head>
	<title>The Lion and the Rabbit</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="ShortStoriesStyle.css">
	<style>
		body {
			margin: 100px;
		}
	</style>
</head>
<body style="background-color:#FFFFE0">
    <h2>The Lion and the Rabbit</h2>
    <center><img src = "TheLionAndTheRabbit.jpg">
    <p>
        Once there was a Lion in the jungle who used to kill 2-3 animals daily for his meal.<br>
		All animals went to him to tell, that daily one of them will come to him for his meal.<br>
		So, the Lion agreed and this started going for many days. One day, it was Rabbit’s turn.<br>
		When he was on his way he saw a well. Now he plans to kill the lion and save himself.<br>
		He went to the lion and told him that, there is another lion who claims to be more powerful than him.<br>
		Then the lion asks the rabbit to take him to that lion. The rabbit takes him to the well and said he lives here.<br>
		When the lion looked in the well he saw his own reflection and jumped in the well and dies.<br>
    </p>
</body>
</html>
