<!DOCTYPE html>  
<html>  
<head>
	<title>The Hunter and the Pigeons</title>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="ShortStoriesStyle.css">
	<style>
		body {
			margin: 100px;
		}
	</style>
</head>
<body style="background-color:#FFFFE0">
    <h2>The Hunter and the Pigeons</h2>
    <center><img src = "TheHunterAndThePigeons.jpg">
    <p>
        One day a hunter sets a net to catch birds and placed grains and rice over the net.<br>
		After some time a flock of pigeons comes by and start eating grains and get caught in the net.<br>
		After some time they started losing hope, then their leader asks them to fly together up in the sky.<br> 
		They did as they were told and carried the net away. The hunter runs after them but they flew away<br> 
		to their friend’s mouse hole. Then the mouse cuts the net and freed the pigeons.<br>
    </p>
</body>
</html>
